env:
  global:
    - CC_TEST_REPORTER_ID=b5370328873f97034f05a0c49b63b7d13b6eeaed129f1bdf17509f183cd6a2f7
language: ruby
rvm:
  - 3.0.3
before_install: gem install bundler -v 2.2.32
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec rake compile
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
